### ISSUE TITLE
I have TypeError: Cannot read properties of null (reading 'isCE') issue

### ISSUE THREAD

**Issue by ngtive** [talkhabi/vue3-persian-datetime-picker#25]
I have this issue where it gives the error:

```
TypeError: Cannot read properties of null (reading 'isCE')
```

I'm using Vue version 3.4 does anyone have any idea why this problem occurs?"

**Comment by mohammad-zr** [comment]
Fixed in vue 3.4.6

**Comment by mehdicodecom** [comment]
It's still happening in nuxt 3.8.2 in development environment
